set -x

##### Download dataset #####

##### Download concepts generated by authors #####
wget -q --show-progress "https://github.com/zijizhu/LM4CV/raw/main/data/CUB_200_2011/cub_attributes.txt"
mv cub_attributes.txt data/CUB_200_2011